# Gemfile
source 'https://rubygems.org'

ruby '3.4.7' # Versión de Ruby que usaremos


# --- Servidor web ---
gem 'sinatra'
gem 'sinatra-contrib'   # para helpers como JSON, reloader, etc.
gem 'puma'              # servidor web rápido, ideal para producción
gem 'dotenv'


# --- GraphQL ---
# motor GraphQL
gem 'graphql'

gem 'batch-loader'      # mejora la eficiencia de resolvers

# --- Middleware y utilidades ---
gem 'rack'
gem 'rack-contrib'
gem 'rack-cors'
gem 'rackup'

# --- JSON y HTTP ---
gem 'json'
gem 'faraday'           # cliente HTTP útil para consumir APIs externas
gem 'httparty'

# --- Autenticación JWT ---
gem 'jwt'               # validación de tokens JWT

#--- Generar pdfs ---
gem 'prawn'
gem 'prawn-table'

# --- Herramientas de desarrollo (solo en modo dev) ---
group :development do
  gem 'rerun'           # reinicia el servidor automáticamente al cambiar archivos
  gem 'fiddle'          # para evitar warning en Ruby 3.4+
end
