# Generated by Django 5.2.7 on 2025-10-25 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id_farmacia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('horario_atencion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_generico', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('principio_activo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=100)),
                ('requiere_receta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id_busqueda', models.AutoField(primary_key=True, serialize=False)),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultados_mostrados', models.IntegerField()),
                ('geolocalizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('farmacia_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=150)),
                ('ubicacion_consultorio', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('dosis', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('duracion_tratamiento', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrescripcion',
            fields=[
                ('id_detalle_prescripcion', models.AutoField(primary_key=True, serialize=False)),
                ('precio_encontrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(max_length=150)),
                ('detalle_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.detallereceta')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicacion_emision', models.CharField(max_length=255)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='login.receta'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.farmacia')),
            ],
        ),
    ]
