# Generated by Django 5.2.7 on 2025-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='tipo_usuario',
            field=models.CharField(default='medico', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_usuario',
            field=models.CharField(default='paciente', max_length=20),
        ),
    ]
