# Generated by Django 5.2.7 on 2025-10-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_medico_tipo_usuario_paciente_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=100),
        ),
        migrations.DeleteModel(
            name='Busqueda',
        ),
    ]
