# Generated by Django 5.2.7 on 2025-11-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_sucursal_ubicacion_delete_busqueda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleprescripcion',
            options={'verbose_name': 'Detalle de Prescripción', 'verbose_name_plural': 'Detalles de Prescripciones'},
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de referencia del producto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleprescripcion',
            name='detalle_receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_busqueda', to='login.detallereceta'),
        ),
        migrations.AlterField(
            model_name='detalleprescripcion',
            name='distancia',
            field=models.DecimalField(decimal_places=2, help_text='Distancia en km desde el paciente', max_digits=6),
        ),
        migrations.AlterField(
            model_name='detalleprescripcion',
            name='fuente',
            field=models.CharField(help_text="De dónde proviene el precio (ej: 'Base de datos', 'Web scraping', etc.)", max_length=150),
        ),
        migrations.AlterField(
            model_name='detalleprescripcion',
            name='precio_encontrado',
            field=models.DecimalField(decimal_places=2, help_text='Precio encontrado (puede venir de ProductoFarmacia o de fuentes externas)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductoFarmacia',
            fields=[
                ('id_producto_farmacia', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto en esta farmacia', max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del precio')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='login.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_por_farmacia', to='login.producto')),
            ],
            options={
                'verbose_name': 'Precio de Producto por Farmacia',
                'verbose_name_plural': 'Precios de Productos por Farmacia',
                'unique_together': {('producto', 'farmacia')},
            },
        ),
        migrations.AddField(
            model_name='detalleprescripcion',
            name='producto_farmacia',
            field=models.ForeignKey(blank=True, help_text='Referencia al precio oficial en ProductoFarmacia (si existe)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.productofarmacia'),
        ),
    ]
