# Generated by Django 5.2.7 on 2025-11-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_detalleprescripcion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productofarmacia',
            name='stock_disponible',
        ),
    ]
