# Generated by Django 5.2.7 on 2025-11-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_productofarmacia_stock_disponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProducto',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_visto', models.DecimalField(decimal_places=2, help_text='Precio que vio el usuario en el momento de la consulta', max_digits=10)),
                ('origen', models.CharField(default='public_search', help_text="Origen de la consulta: 'public_search', 'user_interest', 'saved', 'comparison'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmacia', models.ForeignKey(blank=True, help_text='Farmacia consultada (opcional si es búsqueda general)', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='login.producto')),
                ('producto_farmacia', models.ForeignKey(blank=True, help_text='Referencia al precio oficial consultado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.productofarmacia')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la consulta (null si es anónimo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Producto',
                'verbose_name_plural': 'Consultas de Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_consu_user_id_da7286_idx'), models.Index(fields=['producto', '-created_at'], name='login_consu_product_0cd3bc_idx')],
            },
        ),
    ]
