# Generated by Django 5.2.7 on 2025-11-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_consultaproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_base',
        ),
        migrations.DeleteModel(
            name='ConsultaProducto',
        ),
    ]
